name: Check if nginx config syntax is right
on:
  push:
    branches:
      - main
    tags:
      - v2
      - v1.*

jobs:
  Check-nginx-config:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: sudo cp ./nginx.conf /usr/share/nginx/
      - run: sudo nginx -t -c $PWD/nginx.conf
