name: Check nginx config 
on:
  push:
    branches:
      - main
    tags:
      - v2
      - v1.*

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
       - run: sudo apt install nginx -y
       - run: sudo cp ./nginx.conf /usr/share/nginx/
       - run: sudo nginx -t -c nginx.conf
