name: Check nginx config 
on:
  push:
    branches:
      - main
    tags:
      - v2
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - run: sudo apt install nginx -y
       - run: sudo nginx -t -c $PWD/nginx.conf
